name: Build, publish and release SDK
on:
  workflow_dispatch:
  pull_request:
    branches:
      - release

jobs:
  build-and-publish:
    runs-on: ubuntu-18.04
    steps:
      # Get the code into the container
      - name: Checkout
        uses: actions/checkout@v2
      # Set up the environment
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      # Install pypa/build
      - name: Install pypa/build
        run: python -m pip install build --user
      # Build
      - name: Build a binary wheel and tarball
        run: python -m build --sdist --wheel --outdir dist/
      # Publish to Test PyPI
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{secrets.TEST_PYPI_API_TOKEN}}
          repository_url: https://test.pypi.org/legacy/
