name: Lint and tag before release

on:
  push:
    branches:
    - release

jobs:
  lint-and-tag:
    runs-on: ubuntu-18.04
    steps:
    # Get the code into our container
    - name: Checkout
      uses: actions/checkout@v3
    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        cache: pip
        cache-dependency-path: poetry.lock
        python-version: '3.9'
    # Setup Python
    - name: Setup Poetry
      uses: abatilo/actions-poetry@v2
    # Install dependencies
    - name: Install dependencies
      run: poetry install --no-interaction -E async
    # Make tag
    - name: Make git tag
      run: scripts/tag
